### ISSUE TITLE
websockets extra_headers must be changed to additional_headers

### ISSUE THREAD

**Issue by jimboca** [camect/camect-py#20]
Not sure why I'm seeing this error?

```
2024-11-10 14:21:04.665 Thread-19 (run_until_complete) camect             INFO     __init__:_event_handler: Connecting to Camect hub at 'wss://camect-home-1.lan:443/api/event_ws' ...
2024-11-10 14:21:04.667 Thread-19 (run_until_complete) camect             WARNING  __init__:_event_handler: Unexpected exception: <class 'TypeError'>
```

**Comment by jimboca** [comment]
I added exc_info to the logger warning message which shows the issue:
```
2024-11-10 14:31:04.255 Thread-19 (run_until_complete) camect             INFO     __init__:_event_handler: Connecting to Camect hub at 'wss://camect-home-1.lan:443/api/event_ws' ...
2024-11-10 14:31:04.257 Thread-19 (run_until_complete) camect             WARNING  __init__:_event_handler: Unexpected exception: <class 'TypeError'>
Traceback (most recent call last):
  File "/var/polyglot/pg3/ns/000db952ce50_33/camect/__init__.py", line 250, in _event_handler
    websocket = await websockets.connect(self._ws_uri, ssl=context,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/polyglot/pg3/ns/000db952ce50_33/.local/lib/python3.11/site-packages/websockets/asyncio/client.py", line 441, in __await_impl__
    self.connection = await self.create_connection()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/polyglot/pg3/ns/000db952ce50_33/.local/lib/python3.11/site-packages/websockets/asyncio/client.py", line 367, in create_connection
    _, connection = await loop.create_connection(factory, **kwargs)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: BaseEventLoop.create_connection() got an unexpected keyword argument 'extra_headers'
```

**Comment by jimboca** [comment]
Looks like extra_headers was changed to additional_headers: https://websockets.readthedocs.io/en/stable/faq/client.html#how-do-i-set-http-headers
